### ISSUE TITLE
[BUG]: Preset selection and timescale menus appearing while at the menu if you press E or R

### ISSUE THREAD

**Issue by TeeMeeFe** [yogwoggf/gelly#22]
### GPU

GTX 1660 TI

### Operating System

Windows 10 

### Is this specific to performance?

- [ ] Yes
- [X] No

### Issue Type

Other

### Incident Description

![imagen](https://github.com/yogwoggf/gelly/assets/39315813/174c62f6-3cce-41c3-80a4-571ee0463b09)
![imagen](https://github.com/yogwoggf/gelly/assets/39315813/4ddf731d-c9c9-43b5-8fed-0c1ed8ba035e)

**Comment by TeeMeeFe** [comment]
Basically type anything in console with the gelly gun equipped and you should be able to trigger this bug.

**Comment by yogwoggf** [comment]
Thanks, fixing now

**Comment by yogwoggf** [comment]
Fixed in 1.1.0
