### ISSUE TITLE
[BUG] Laptop GPU tends to have abysmal performance

### ISSUE THREAD

**Issue by benrut123** [yogwoggf/gelly#26]
### GPU

Nvidia 4060

### Operating System

windows 11

### Is this specific to performance?

- [X] Yes
- [ ] No

### Issue Type

Low FPS

### Incident Description

game lags really bad after like 100 gelly particles but can handle gwater2 really fine.

### Log

Not getting any logs. just fps.

**Comment by benrut123** [comment]
Note: sometimes it doesnt lag but most of the times it lags

**Comment by benrut123** [comment]
didnt mean

**Comment by benrut123** [comment]
iujehywgr

**Comment by yogwoggf** [comment]
I've jotted this down as a result of NVAPI extension usage in FleX, will try to fix in a later version

**Comment by yogwoggf** [comment]
I've disabled such extensions, therefore as a precaution to eliminate confusion about if this bug really exists, I'll close this issue. Please make a new one if you observe this behavior with v1.3.0
