### ISSUE TITLE
[BUG]: Particle queue eventually stops evaluating particle spawns fast enough

### ISSUE THREAD

**Issue by Cubature1** [yogwoggf/gelly#27]
### GPU

nVIDIA RTX 3050

### Operating System

Windows 11

### Is this specific to performance?

- [ ] Yes
- [ ] No

### Issue Type

Other

### Incident Description

![20240603231316_1](https://github.com/yogwoggf/gelly/assets/64175394/3833354a-7106-41cb-8d14-d1140a7bb8e3)
When enough particles are spawned, the gelly gun becomes unresponsive to inputs.

**Comment by Cubature1** [comment]
Seems to fix itself if enough time goes by without spawning liquid.

**Comment by yogwoggf** [comment]
Yeah this is kinda sucky, will just remove the 'feature' that caused this

**Comment by yogwoggf** [comment]
Triaged in #51

**Comment by yogwoggf** [comment]
Fixed in #52
