### ISSUE TITLE
[BUG]: No particle friction

### ISSUE THREAD

**Issue by Cubature1** [yogwoggf/gelly#28]
### GPU

RTX 3050

### Operating System

Win. 11

### Is this specific to performance?

- [ ] Yes
- [X] No

### Issue Type

Other

### Incident Description

Particles have no friction.

**Comment by yogwoggf** [comment]
They have friction, however #53 means that the friction needs to be increased--and sometimes a slippery fluid might be desirable for some users. Either way, the friction will be strengthened for most presets in a later, bigger update for fluid behavior--it's not worth making a new PR for such a minimal change when others are planned.
