### ISSUE TITLE
[BUG]: NaN values cause collision to be unstable and tunnel particles

### ISSUE THREAD

**Issue by portanz** [yogwoggf/gelly#29]
### GPU

GTX 1660 TI

### Operating System

Windows 11

### Is this specific to performance?

- [ ] Yes
- [X] No

### Issue Type

Other

### Incident Description

Liquids clip trough the map at high speeds

**Comment by yogwoggf** [comment]
Determined this is because the map geometry in FleX can have a NaN angular momentum attached to it
