### ISSUE TITLE
[BUG]: Gmod usually crashes when loading a map

### ISSUE THREAD

**Issue by vill25** [yogwoggf/gelly#31]
### GPU

NVIDIA GeForce GTX 1660 Ti

### Operating System

Windows 10

### Is this specific to performance?

- [ ] Yes
- [X] No

### Issue Type

Crash

### Incident Description

basically what the title says
''Gmod usually crashes when loading a map''

### Log

Sorry but i can't do this without screwing it up 💀

**Comment by yogwoggf** [comment]
Solved in v1.1.2

**Comment by WetRat2014** [comment]
broken still, i have latest
