### ISSUE TITLE
[BUG]: RTV gets deleted

### ISSUE THREAD

**Issue by Cubature1** [yogwoggf/gelly#33]
### GPU

RTX 3050

### Operating System

Windows 11

### Is this specific to performance?

- [ ] Yes
- [X] No

### Issue Type

Other

### Incident Description

After a period of time, Gelly stops rendering particles. Might have something to do with ULib, as when the issue occurs ULib spits errors.
![image](https://github.com/yogwoggf/gelly/assets/64175394/102163aa-02b2-4d69-97af-52311a568f9c)
Errors seem to appear every tick in game as long as there are particles in the world.
(Game crashed while writing report)

### Log

[gelly-log-2024-06-05.log](https://github.com/user-attachments/files/15573682/gelly-log-2024-06-05.log)
68 thousand lines of errors ^

**Comment by yogwoggf** [comment]
Strange, this is an evil bug that won't go away. Were you on v1.2.0? if so, could you try again with it?

**Comment by Cubature1** [comment]
Bug did not appear past 1.1.2.

**Comment by yogwoggf** [comment]
Hmmm.. this bug generally appears to be related to the buggy max particles change function which is now fixed... but I don't have concrete evidence that it cannot happen again.. so I will just close this and if it arises again, please make a new issue.
