### ISSUE TITLE
[BUG]: Gelly will render in wireframe mode as a result of state leakage from rendering a wireframe prop

### ISSUE THREAD

**Issue by Cubature1** [yogwoggf/gelly#34]
### GPU

RTX 3050

### Operating System

Win. 11

### Is this specific to performance?

- [ ] Yes
- [X] No

### Issue Type

Other

### Incident Description

Having an object in the world with the wireframe material causes Gelly's rendering to become broken (Generally becoming a bunch of stretched lines)

**Comment by Cubature1** [comment]
It is **only** the wireframe material.

**Comment by yogwoggf** [comment]
Fixed in #54
