### ISSUE TITLE
[BUG]: Some props have 90-degree rotated collision meshes

### ISSUE THREAD

**Issue by cast-e** [yogwoggf/gelly#37]
### GPU

NVIDIA Geforce RTX 3060

### Operating System

Windows 11

### Is this specific to performance?

- [ ] Yes
- [X] No

### Issue Type

Other

### Incident Description

Some props like "models\props_phx\huge\road_long.mdl" and "models\props_lab\blastdoor001a.mdl" have 90 degrees offset of collision with gelly.

**Comment by yogwoggf** [comment]
Yeah, this is a GMod bug, will look into fixing but to be honest it's low priority.

**Comment by Derpius** [comment]
@yogwoggf are you failing to apply the bind pose to rigid meshes?

Props like the gmod logo have their root bone rotated 90 degrees relative to the mesh data

**Comment by yogwoggf** [comment]
> @yogwoggf are you failing to apply the bind pose to rigid meshes?
> 
> Props like the gmod logo have their root bone rotated 90 degrees relative to the mesh data

Just read this as I was triaging, definitely it. Should be a quick win given this info.

**Comment by yogwoggf** [comment]
Triaged in #75
