### ISSUE TITLE
[BUG]: Gelly insta-crashes with a Lua Panic, "7"

### ISSUE THREAD

**Issue by kingsman-debug** [yogwoggf/gelly#39]
### GPU

AMD Radeon RX 560

### Operating System

Windows 10

### Is this specific to performance?

- [ ] Yes
- [X] No

### Issue Type

Crash

### Incident Description

When i run GMOD it just crashes when i load a map like construct, i tried lowering my graphics and closing all apps yet it keeps showing me a lua error
![image](https://github.com/yogwoggf/gelly/assets/171945325/0d9fdd4d-e83b-46f1-9fe9-8d47beb11fe7)

### Log

Lua Panic! Something went horribly wrong!

*7*

**Comment by yesthisaccountisuseless** [comment]
this happens to me too 
ngl idk what to do

**Comment by kingsman-debug** [comment]
> this happens to me too ngl idk what to do

lets wait for the dev to respond, he knows his stuff, i think its maybe because my graphics card is too weak but lets see his reply

**Comment by yogwoggf** [comment]
Please try release [v1.2.3](https://github.com/yogwoggf/gelly/releases/tag/v1.2.3) and send your logs if it crashes. This is an ongoing issue with no visible solution in sight due to the unpredictability of the bug

**Comment by kingsman-debug** [comment]
I'll wait until the mod is fully fixed, i'm not good with stuff based around Gmod

**Comment by skibiditoiletz** [comment]
n

**Comment by skibiditoiletz** [comment]
shut up nigger

**Comment by yogwoggf** [comment]
Fixed >= v1.2.17
