### ISSUE TITLE
[BUG]: Fluid sticks to some weird pattern

### ISSUE THREAD

**Issue by SolsticeSpectrum** [yogwoggf/gelly#41]
### GPU

GTX 1060

### Operating System

Windows 10

### Is this specific to performance?

- [ ] Yes
- [X] No

### Issue Type

Other

### Incident Description

As you can see the fluid has some weird patterns in it, probably math issue
![image](https://github.com/yogwoggf/gelly/assets/38611351/2a86ab2d-c5d6-4b1f-84af-25c3a902df92)

**Comment by SolsticeSpectrum** [comment]
It might be the polygons that the ground is made of

**Comment by Derpius** [comment]
This will be solved by #36, which is for the work needed to merge map faces or use the BSP's physics collider lump (requires an update to `BSPParser`)
