### ISSUE TITLE
[BUG]: The player hand is scuffed with gelly gun

### ISSUE THREAD

**Issue by SolsticeSpectrum** [yogwoggf/gelly#42]
### GPU

GTX 1060

### Operating System

Windows 10

### Is this specific to performance?

- [ ] Yes
- [X] No

### Issue Type

Other

### Incident Description

The hand is really messed up

![image](https://github.com/yogwoggf/gelly/assets/38611351/adcc3d2a-a4d0-4171-8c5b-d7fded98c24f)

**Comment by yogwoggf** [comment]
Triaged in #48

**Comment by SolsticeSpectrum** [comment]
@yogwoggf You forgot to fix the liquifier too
![image](https://github.com/yogwoggf/gelly/assets/38611351/3b016489-dbcb-40fa-8203-2434b3715976)
