### ISSUE TITLE
Rework issue templates

### ISSUE THREAD

**Issue by Derpius** [yogwoggf/gelly#60]
### Context

- The repository has a number of form-based templates which do things like tagging with `ticket` and assigning @yogwoggf 
- This has a few problems
  - The separate text entry boxes cannot be previewed at once - Forms are great for user-submitted issues, but we're using Discord for that now. Engineers can be trusted with a more freeform template
  - The `ticket` label is redundant now that we're using Discord
  - Assigning @yogwoggf implies the issue is being worked on. Assignment should be used to communicate that an issue has been picked up by the assignee (this also doesn't work if more than 1 regular contributor exists)

### Scope

- Remove the three distinct "ticket" templates
- Create a new non-form template with the default content matching the structure of these ticket forms
- Remove the `[TICKET]` prefix from the issue title default
- **Could:** Update the existing user reports to match the style and detail of the ticket template

### Acceptance Criteria

- Singular flexible issue template with `Context`, `Scope`, `Acceptance Criteria` and `Other` sections
  - Notes included as HTML comments where it seems useful
- Issue is unassigned by default when created
- Issue is not labelled by default when created - A prompt should be added in the issue description to tag with the relevant focus (aka capability)
- Issue title is blank by default
- All of the previous form templates are removed, leaving only the newly created "Engineering ticket" and the two links to Discord

**Comment by Derpius** [comment]
High priority as this impacts all tickets being created

**Comment by yogwoggf** [comment]
> [!NOTE] 
Its actually being discouraged by GitHub--doesn't seem like a huge issue though. They want you to use issue forms or the restricted markdown template builder (which does not support HTML comments).

**Comment by Derpius** [comment]
It’s probably discouraged for open source projects where contributors might not be familiar with the approach when raising issues

in this case it’s purely for regular maintainers to track work, so i cant see any harm - on the other hand, there’s a lot of harm to devx by using a restrictive template
